;;; vicare_site_dir.scm --- Returns the Vicare library directory
;;; coding: utf-8

;;; vicare_site_dir - scheme script to get the Vicare library directory
;;; Copyright (C) 2016 Freja Nordsiek
;;;
;;; This program is free software: you can redistribute it and/or modify
;;; it under the terms of the GNU General Public License as published by
;;; the Free Software Foundation, either version 3 of the License, or
;;; (at your option) any later version.
;;;
;;; This program is distributed in the hope that it will be useful,
;;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
;;; GNU General Public License for more details.
;;;
;;; You should have received a copy of the GNU General Public License
;;; along with this program.  If not, see <http://www.gnu.org/licenses/>.

;;; As a special exception to the GNU General Public License, if you
;;; distribute this file as part of a program that contains a
;;; configuration script generated by Autoconf, you may include it under
;;; the same distribution terms that you use for the rest of that program.


;;; Writes the binary library search path to standard out unless it
;;; starts with ${exec_prefix} in which case the program exits with
;;; an error.

(import (rnrs base (6))
        (rnrs io ports (6))
        (rnrs io simple (6))
        (rnrs programs (6))
        (vicare libraries))
(let* ((s (car (library-binary-search-path)))
       (exclude-s "${exec_prefix}")
       (len-exclude-s (string-length exclude-s)))
  (if (and (>= (string-length s) len-exclude-s)
           (string=? (substring s 0 len-exclude-s) exclude-s))
      (exit 0)
      (begin
        (display s)
        (flush-output-port (current-output-port)))))
