;;; vicare_site_dir.scm --- Returns the Vicare library directory
;;; coding: utf-8

;;; unit-test-tap - scheme unit testing framework with TAP output
;;; Copyright (C) 2016 Freja Nordsiek
;;;
;;; This library is free software; you can redistribute it and/or
;;; modify it under the terms of the GNU Lesser General Public
;;; License as published by the Free Software Foundation; either
;;; version 2.1 of the License, or any later version.
;;;
;;; This library is distributed in the hope that it will be useful,
;;; but WITHOUT ANY WARRANTY; without even the implied warranty of
;;; MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
;;; Lesser General Public License for more details.
;;;
;;; You should have received a copy of the GNU Lesser General Public
;;; License along with this library; if not, write to the Free Software
;;; Foundation, Inc., 51 Franklin Street, Fifth Floor,
;;; Boston, MA  02110-1301  USA

;;; As a special exception to the GNU Lesser General Public License, if you
;;; distribute this file as part of a program that contains a
;;; configuration script generated by Autoconf, you may include it under
;;; the same distribution terms that you use for the rest of that program.


;;; Writes the binary library search path to standard out unless it
;;; starts with ${exec_prefix} in which case the program exits with
;;; an error.

(import (rnrs base (6))
        (rnrs io ports (6))
        (rnrs io simple (6))
        (rnrs programs (6))
        (vicare libraries))
(let* ((s (car (library-binary-search-path)))
       (exclude-s "${exec_prefix}")
       (len-exclude-s (string-length exclude-s)))
  (if (and (>= (string-length s) len-exclude-s)
           (string=? (substring s 0 len-exclude-s) exclude-s))
      (exit 0)
      (begin
        (display s)
        (flush-output-port (current-output-port)))))
